alias gl='git log --all --graph --decorate --stat'
#alias tmux='TERM=xterm-256color tmux'
alias tmux='TERM=xterm-256color tmux -u'
alias vless='/usr/share/vim/vim81/macros/less.sh'
alias rm='trash-put'
